### ISSUE TITLE
Missing Table Name for Fields in JOIN Queries Throws Error

### ISSUE THREAD

**Issue by larsenweigle** [stanford-oval/suql#17]
### Description
When executing certain SQL JOIN queries without specifying the table name for a field, the query unexpectedly fails with an error. This occurs even when the column name specified is unique across the joined tables. Below are examples to illustrate the issue:

For these examples,`field1` is a unique field name across all tables.

#### Working Example
This query executes without any issues:
```sql
SELECT field1, ... FROM ... JOIN table2 ON ... answer(table2.field1, 'foo bar') = 'yes'
```

#### Failing Example
This similar query results in an error because `field1` does not explicitly specify the table name:
```sql
SELECT field1, ... FROM ... JOIN table2 ON ... answer(field1, 'foo bar') = 'yes'
```

### Error Message
Here is the exact error message produced:
```
Bad argument, expected a ast.Node instance or a tuple
Traceback (most recent call last):
  File "/home/larsen/course-companion/sql_free_text_support/execute_free_text_sql.py", line 1086, in suql_execute_single
    visitor(root)
  File "/home/larsen/course-companion/sql_free_text_support/execute_free_text_sql.py", line 160, in __call__
    super().__call__(node)
  File "/home/larsen/.local/lib/python3.8/site-packages/pglast/visitors.py", line 317, in __call__
    result = method(ancestors, node)
  File "/home/larsen/course-companion/sql_free_text_support/execute_free_text_sql.py", line 185, in visit_SelectStmt
    results, column_info = analyze_SelectStmt(node, self.cache)
  File "/home/larsen/course-companion/sql_free_text_support/execute_free_text_sql.py", line 1040, in analyze_SelectStmt
    return execute_and(sql_dnf_predicates, node, limit, cache)
  File "/home/larsen/course-companion/sql_free_text_support/execute_free_text_sql.py", line 1002, in execute_and
    structural_res, column_info = execute_structural_sql(node, structural_predicates, cache)
  File "/home/larsen/course-companion/sql_free_text_support/execute_free_text_sql.py", line 828, in execute_structural_sql
    _, columns = execute_structural_sql(
  File "/home/larsen/course-companion/sql_free_text_support/execute_free_text_sql.py", line 847, in execute_structural_sql
    replace_original_target_visitor(original_node.targetList)
  File "/home/larsen/course-companion/sql_free_text_support/execute_free_text_sql.py", line 799, in __call__
    super().__call__(node)
  File "/home/larsen/.local/lib/python3.8/site-packages/pglast/visitors.py", line 310, in __call__
    ancestors, node = generator.send(None)
  File "/home/larsen/.local/lib/python3.8/site-packages/pglast/visitors.py", line 343, in iterate
    raise ValueError('Bad argument, expected a ast.Node instance or a tuple')
ValueError: Bad argument, expected a ast.Node instance or a tuple
```

- The issue appears to be with how the query parser handles fields without table name prefixes in the presence of JOIN operations.
- This error does not occur when the table name is explicitly mentioned alongside the field name.

**Comment by george1459** [comment]
This should have been fixed in version `1.1.7a6`. You should see returned results as well.
